### ISSUE TITLE
Error after fresh installation

### ISSUE THREAD

**Issue by x3evolutionx** [GameserverApp/Community-Website#3]
after installing, i only get 500 error on the website. 

This is the only error in the nginx error.log

2021/07/01 02:04:03 [error] 794#794: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught BadMethodCallException: This cache store does not support tagging. in /var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:355
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(305): Illuminate\Cache\Repository->tags()
#1 /var/www/app/GameserverApp/Api/OAuthApi.php(238): Illuminate\Cache\CacheManager->__call()
#2 /var/www/app/GameserverApp/Api/OAuthApi.php(128): GameserverApp\Api\OAuthApi::cache()
#3 /var/www/app/GameserverApp/Api/OAuthApi.php(107): GameserverApp\Api\OAuthApi::request()
#4 /var/www/app/GameserverApp/Api/Client.php(687): GameserverApp\Api\OAuthApi::guestRequest()
#5 /var/www/app/GameserverApp/Helpers/SiteHelper.php(117): GameserverApp\Api\Client::domain()
#6 /var/www/storage/framework/views/d64fa19ade75384933f4c7bed7c755260d3b166e.php(23): GameserverApp\Helpers\SiteHelper::background()
#7 /var/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/var/www/st...PHP message: PHP Fatal error:  Uncaught BadMethodCallException: This cache store does not support tagging. in /var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:355

**Comment by mvaessen** [comment]
Hi!

It seems that the issue is was caused by 2 missing files (empty), that were needed.
I've added a couple lines to the install script which should resolve the problem.

You can run the same lines, to fix the problem on your end. Alternatively you can reinstall the droplet if you prefer.

```mkdir -p /var/www/public/js
touch /var/www/public/js/app.js```

After running that on the droplet, run `npm run production` to generate the assets.

Thanks for reporting!

**Comment by x3evolutionx** [comment]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /root/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-01T07_30_45_512Z-debug.log

**Comment by mvaessen** [comment]
Did you do a full droplet reinstall or only ran the lines?
If you haven't yet done a full droplet reinstall, please try that.

**Comment by x3evolutionx** [comment]
I tried adding first, then reinstalled.

**Comment by mvaessen** [comment]
I noticed I put the lines too far down in the script. So this might have caused the reinstall to fail.

I just finished setting up a completely new droplet (removed the old one) and all seems to be doing fine now. If reinstalling your droplet with LEMP isnt working, please try destroying this droplet and create a new one (assuming this droplet was only used for the community website).

**Comment by x3evolutionx** [comment]
/var/www/install-ssl.sh: line 1: certbot: command not found
sed: can't read /etc/nginx/sites-enabled/digitalocean: No such file or directory
nginx: unrecognized service

**Comment by mvaessen** [comment]
seems that it's not running on a LEMP droplet. Please note that reinstalling a droplet will not reinstall LEMP, but only Ubuntu 20.04.

Please try on a new droplet and see if it still happens. I can't reproduce this issue on a new droplet running Ubuntu 20.04 LEMP

**Comment by x3evolutionx** [comment]
i had used the marketplace LEMP install. let me redo and see. ill update ya

**Comment by x3evolutionx** [comment]
ok so everything seems like it installed properly no errors but when i go to the DNS subdomain i setup for the droplet, it only gives me This page isn’t workingpanel.pve.thearkive.net is currently unable to handle this request. HTTP ERROR 500

**Comment by x3evolutionx** [comment]
This was in the error.log for nginx again.

2021/07/01 08:20:41 [error] 7157#7157: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught BadMethodCallException: This cache store does not support tagging. in /var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:355
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(305): Illuminate\Cache\Repository->tags()
#1 /var/www/app/GameserverApp/Api/OAuthApi.php(238): Illuminate\Cache\CacheManager->__call()
#2 /var/www/app/GameserverApp/Api/OAuthApi.php(128): GameserverApp\Api\OAuthApi::cache()
#3 /var/www/app/GameserverApp/Api/OAuthApi.php(107): GameserverApp\Api\OAuthApi::request()
#4 /var/www/app/GameserverApp/Api/Client.php(687): GameserverApp\Api\OAuthApi::guestRequest()
#5 /var/www/app/GameserverApp/Helpers/SiteHelper.php(117): GameserverApp\Api\Client::domain()
#6 /var/www/storage/framework/views/d64fa19ade75384933f4c7bed7c755260d3b166e.php(23): GameserverApp\Helpers\SiteHelper::background()
#7 /var/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/var/www/st...PHP message: PHP Fatal error:  Uncaught BadMethodCallException: This cache store does not support tagging. in /var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:355
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(305): Illuminate\Cache\Repository->tags()
#1 /var/www/app/GameserverApp/Api/OAuthApi.php(238): Illuminate\Cache\CacheManager->__call()
#2 /var/www/app/GameserverApp/Api/OAuthApi.php(128): GameserverApp\Api\OAuthApi::cache()
#3 /var/www/app/GameserverApp/Api/OAuthApi.php(107): GameserverApp\Api\OAuthApi::request()
#4 /var/www/app/GameserverApp/Api/Client.php(687): GameserverApp\Api\OAuthApi::guestRequest()
#5 /var/www/app/GameserverApp/Helpers/SiteHelper.php(117): GameserverApp\Api\Client::domain()
#6 /var/www/storage/framework/views/d64fa19ade75384933f4c7bed7c755260d3b166e.php(23): GameserverApp\Helpers\SiteHelper::background()
#7 /var/www/vendor/laravel/framework/src/Illuminate/View/

**Comment by mvaessen** [comment]
Ah, I think this might be caused by one of the updates I pushed out a while ago.
Basically the cache used is being tagged, to easily invalidate certain caches.

But for the basic caching on a self-hosted community website the system uses disk caching.

The easiest way to fix this is by installing Redis on the droplet using `sudo apt install redis-server`. 
After installing edit `/var/www/.env` and add 
```
CACHE_DRIVER=redis
REDIS_HOST=127.0.0.1
```

That should resolve the problem. I'll make sure to update the droplet install script so this will be configured automatically in the future.

Let me know if that worked.

**Comment by x3evolutionx** [comment]
Yup! that fixed it, I guess not many people use the API custom website part of things yet. Thanks for your time man!

**Comment by mvaessen** [comment]
Most people take the easy route and use the hosted version indeed, or go with the PHP API Wrapper.

Happy to help and thank you for pointing out the issues 👍
